import React, {useEffect, useMemo, useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import MainHeader from '../components/main-header'
import ProgressBar from '../components/progress-bar/index'
import SurnamesServices  from '../services/surnames'
import style from '../styles/Home.module.css'

export default function Home() {
  const [surnames, setSurnames] : any = useState({})
  const [consolidatedSurnames, setConsolidatedSurnames] = useState([])
  const [isProgressBarVisible, setIsProgressBarVisible] = useState(true)
  const [total, setTotal] : any = useState(0)
  const [searchParam, setSearchParam] : any = useState(null)
  const [searchResults, setSearchResults]: any = useState([])
  const getSurnames = () => {
    return SurnamesServices.fetchData().then(res => res)
  }

  const search = (e:any) => {
    const res = [...consolidatedSurnames]
    const filteredResults = res.filter((val: string, index) => {
      return val ? val.toLowerCase().indexOf(e.target.value.toLowerCase()) != -1 : false
    })

    setSearchResults(filteredResults)
    setSearchParam(e.target.value.toLowerCase())
  }

  useEffect(() => {
    getSurnames ().then(res => {  
      setSurnames(res)
      let x: object;
      let tot: number = 0;
      let sur: any = []
      for(x of res) {
        tot = tot + Object.values(x)[0]?.length
        if(Object.values(x)[0]) sur = sur.concat(Object.values(x)[0])
      }

      setTotal(tot)
      setConsolidatedSurnames(sur)
      setTimeout(() => setIsProgressBarVisible(false), 2000)
    })
  },[])

  return (
    <div style={{paddingBottom: '20vh'}}>
      <Head>
        <title>Catalogo Alfabetico de Apellidos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='wrapper'>
        <MainHeader/>
        <ProgressBar show={isProgressBarVisible}/>
      </div>

      {!searchParam && <main className='mt-3'>
        <div className="container">
          <div className='col col-12 text-center mt-5'>
            <img src='/logo.png' width={250} className="mt-3"/>
          </div>
          <div className="row">
            <div className="col-sm text-center">
              <h1 className='headings'>
                <span className='text-red'>C</span>atalogo <span className='text-red'>A</span>lfabetico de <span className='text-red'>A</span>pellidos
              </h1>
              <p className='text-muted small'>List of surnames in the Philippines and other islands of Spanish East Indies published in the mid-19th century</p>
            </div>
          </div>
        </div>
      </main> }

      {searchParam && 
        <div className="container">
          <div className="row mt-5">
            <div className="col-md-2 col-8 offset-2 text-center">
              <img src='/logo.png' width={'50%'} className="mt-3" style={{minWidth: '100px'}}/>
            </div>
            <div className="col-md-5 col-8 offset-2 offset-md-0">
              <h3 className='headings mt-4'>
                <span className='text-red'>C</span>atalogo <span className='text-red'>A</span>lfabetico de <span className='text-red'>A</span>pellidos
              </h3>
              <p className='text-muted small'>List of surnames in the Philippines and other islands of Spanish East Indies published in the mid-19th century</p>
            </div>
          </div>
        </div>
      }

      {isProgressBarVisible && <main className='text-center p-5 text-muted'>
        <p><i className='fa fa-spinner'/> Loading all the necessary information. Please wait . . .</p>
      </main> }

      {!isProgressBarVisible && <main className='visible'>
        <div className='col col-md-6 col-8 offset-2 offset-md-3 mt-3'>
          <div className="input-group mb-3">
            <input type="text" className="form-control" placeholder="TYPE YOUR SURNAME HERE" onChange={search}/>
            <div className="input-group-append">
              <button className="btn btn-outline-secondary" type="button" disabled>
                <i className='fa fa-search'/>
              </button>
            </div>
          </div>
        </div>
      </main> }

     {(searchParam && searchResults) && <main className='visible'>
        <div className='col col-md-6 col-8 offset-2 offset-md-3 mt-3 small'>
          <div className='container'>
              {searchResults && searchResults.sort((a: any,b:any) => {
                return (100 - (b.length - searchParam.length)) - (100 - (a.length - searchParam.length))
              }).map((el: string, index: number) => {
                if(index > 10) return
                return !index ?
                  <div className={`row alert alert-success ${style.alertSuccess}`}>
                    <div className='col-6' key={index}><b><i className='fa fa-trophy'/> {el}</b></div>
                    <div className='col-6 pl-3'>
                      <i className='fa fa-check-circle'/> {(el && searchParam) && (100 - (el.length - searchParam.length))}% matched
                    </div>
                  </div> : 
                  <div className='row'>
                    <div className='col-6' key={index}><b>{el}</b></div>
                    <div className='col-6'>{(el && searchParam) && (100 - (el.length - searchParam.length))}% matched</div>
                  </div>
              })}
          </div>
        </div>
      </main> }
    </div>
  )
}
